apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfc-e2e-collector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "sfc-e2e-collector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sfc-e2e-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sfc-e2e-collector.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "sfc-e2e-collector.envs" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
