apiVersion: v1
kind: Service
metadata:
  name: {{ include "sfc-e2e-collector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "sfc-e2e-collector.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sfc-e2e-collector.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
