image:
  repository: euidong/sfc-e2e-collector
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

envs: {}
  # ROOT_PATH: <- If you want to override this, specify here. default is '/{{ "sfc-e2e-collector.fullname" }}'.

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "1"
    memory: "1Gi"

replicaCount: 1

service:
  type: ClusterIP
  port: 80
